# Nome da aplicação
spring.application.name=nassau

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nassau_db
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha

# Configuração JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Porta da aplicação
server.port=8080